# Generated by Django 5.0.6 on 2024-05-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
    ]
