# Generated by Django 5.0.6 on 2024-05-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_short_description_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='slug',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productvariationcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
