# Generated by Django 5.0.6 on 2024-05-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_productvariation_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Category'},
        ),
    ]
