# Generated by Django 5.0.6 on 2024-05-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
