# Generated by Django 5.0.6 on 2024-05-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productvariation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
