# Generated by Django 5.0.6 on 2024-05-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery'), ('stripe', 'Stripe'), ('sslcommerz', 'SSLCommerz'), ('bkash', 'bKash')], default='cash_on_delivery', max_length=100),
        ),
    ]
