# Generated by Django 5.0.6 on 2024-06-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refunds',
            old_name='transaction_id',
            new_name='transaction',
        ),
    ]
