# Generated by Django 5.0.6 on 2024-06-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0002_rename_transaction_id_refunds_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refunds',
            old_name='transaction',
            new_name='transaction_id',
        ),
    ]
