# Generated by Django 5.0.6 on 2024-05-21 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitems_cart_remove_cartitems_product_and_more'),
        ('couponcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='couponcode.coupon'),
        ),
    ]
