# Generated by Django 5.0.6 on 2024-05-22 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('store', '0006_productvariation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='product_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.productvariation'),
        ),
    ]
