# Generated by Django 5.0.6 on 2024-05-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orders_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
